name: sample workflow push to main branch
on:
  push:
    branches:
    - main
jobs: 
  runs-on: ubuntu-latest  
  steps:
    - uses: actions/checkout@v4
	- uses: actions/setup-node@v4
	  with:
	    node-version: '20'
	- run npm install -g cats
	- run: cats -v
